---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-secureboot
  name: vmi-secureboot
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
    features:
      acpi: {}
      smm:
        enabled: true
    firmware:
      bootloader:
        efi:
          secureBoot: true
    machine:
      type: ""
    resources:
      requests:
        memory: 1Gi
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: index.docker.io/seawolf2/microlivecd-container-disk-demo:mybuild
    name: containerdisk
